// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Person = {};

var Student = {};

var Computer = {};

var us_1 = {
  hd: undefined,
  tl: {
    hd: undefined,
    tl: /* [] */0
  }
};

var us = {
  hd: undefined,
  tl: us_1
};

function i(param) {
  
}

var name = undefined.name;

var p;

var s;

var c;

var s_as_p;

var pu;

var cu;

var p_;

var s_;

var c_;

exports.Person = Person;
exports.Student = Student;
exports.Computer = Computer;
exports.p = p;
exports.s = s;
exports.c = c;
exports.s_as_p = s_as_p;
exports.us = us;
exports.i = i;
exports.name = name;
exports.pu = pu;
exports.cu = cu;
exports.p_ = p_;
exports.s_ = s_;
exports.c_ = c_;
/* name Not a pure module */
