// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Union = {};

var Intersection = {};

var Any = {};

var Unknown = {};

var Never = {};

var Void = {};

var $$Number = {};

var $$Symbol = {};

exports.Union = Union;
exports.Intersection = Intersection;
exports.Any = Any;
exports.Unknown = Unknown;
exports.Never = Never;
exports.Void = Void;
exports.$$Number = $$Number;
exports.$$Symbol = $$Symbol;
/* No side effect */
